# Generated by Django 5.0 on 2023-12-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_remove_product_categoryat_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='categoryAt',
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_at',
            field=models.ManyToManyField(related_name='productAttribute', through='eCommerce.ProductAttribute', to='eCommerce.attribute'),
        ),
        migrations.DeleteModel(
            name='CategoryAt',
        ),
    ]
