# Generated by Django 5.0 on 2023-12-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='product/%Y/%m'),
        ),
    ]
