# Generated by Django 5.0 on 2023-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0008_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avt',
            field=models.ImageField(default=None, null=True, upload_to='account/%Y/%m'),
        ),
    ]
