# Generated by Django 5.0 on 2023-12-24 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0014_alter_attribute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avt',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avt'),
        ),
    ]
