# Generated by Django 5.0 on 2023-12-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0015_alter_account_avt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_cart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_account',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_order',
            field=models.ManyToManyField(related_name='product_order', through='eCommerce.OrderDetail', to='eCommerce.order'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
