# Generated by Django 5.0 on 2023-12-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0017_alter_order_paymenttype_alter_order_shippingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
