# Generated by Django 5.0 on 2024-01-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0020_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
    ]
