# Generated by Django 5.0 on 2024-01-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0022_hinh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hinh',
        ),
    ]
