# Generated by Django 5.0 on 2024-01-12 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0026_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='orderDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerce.orderdetail'),
        ),
    ]
