# Generated by Django 5.0 on 2024-01-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0027_alter_commentproduct_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='eCommerce.product'),
        ),
    ]
