# Generated by Django 5.0 on 2024-01-15 17:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0028_alter_commentproduct_rating_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avt',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avt'),
        ),
    ]
