# Generated by Django 5.0 on 2024-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=500, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
