# Generated by Django 5.0 on 2024-01-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_alter_paymentvnpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('bill_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_transactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='eCommerce.order')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentVNPay',
        ),
    ]
