# Generated by Django 5.0 on 2024-01-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_bill_delete_paymentvnpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_desc',
        ),
    ]
