# Generated by Django 5.0 on 2024-01-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_bill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
