# Generated by Django 5.0 on 2024-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_alter_bill_bill_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_review',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='status_review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
