# Generated by Django 5.0 on 2024-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0010_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
