# Generated by Django 5.0 on 2024-02-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0011_account_google_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='google_user_id',
            new_name='social_user_id',
        ),
    ]
