# Generated by Django 5.0 on 2024-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0012_rename_google_user_id_account_social_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
