# Generated by Django 5.0 on 2024-02-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0013_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
