# Generated by Django 5.0 on 2024-02-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0014_product_tag_end_date_product_tag_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewStore',
        ),
    ]
